apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubeadm-token-notificator
  name: kubeadm-token-notificator
  namespace: kube-system
spec:
  #serviceAccount: admin
  containers:
  - name: kubeadm-token-notificator
    image: alicey/kubeadm-token-notificator:latest
    volumeMounts:
    - name: kubeconfig
      mountPath: "/root/.kube"
      readOnly: true
  volumes:
    - name: kubeconfig
      configMap:
        name: kubeconfig
        items:
        - key: "config"
          path: "config"
---
apiVersion: v1
kind: Service
metadata:
  name: kubeadm-token-notificator-nodeport-service
  namespace: kube-system
spec:
  selector:
    app: kubeadm-token-notificator
  ports:
    - port: 32765
      nodePort: 32765
  type: NodePort
