apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubectl
  name: kubectl-pod
spec:
  serviceAccount: admin
  containers:
  - name: kubectl
    image: alicey/kubectl:latest
    command:
    - tail
    - -f
    - /dev/null
    volumeMounts:
    - name: kubeconfig
    mountPath: "/root/.kube/config"
      readOnly: true
      volumes:
      - name: kubeconfig
        configMap:
          name: kubeconfig
          items:
          - key: "config"
            path: "config"